### PR TITLE
React-app-rewired issue #446

### PR DESCRIPTION
**Pull request by dawnmist**
Trying to get more detail on why the tests are currently hanging in Travis CI.

Please do not merge. ;)

### CODE REVIEW

**Comment by NoPhaseNoKill** [comment]
Thanks a lot for the help. Appreciate it :)

**Comment by dawnmist** [comment]
You're welcome - since it was all running normally when run locally, I thought the best way to be able to test what was happening was via a dummy pull request since that all runs inside Travis.

**Comment by NoPhaseNoKill** [comment]
The other option you have (which I can get out of, if it helps) - is dockering directly into the container

**Comment by NoPhaseNoKill** [comment]
Easiesy way to do this is the following:
1) Open terminal
2) BUILDID="build-$RANDOMNUMBERHERE"
3) INSTANCE="travisci/ci-sardonyx:packer-1553530531-f909ac5" (this can also be found by looking at the build output of any of the failing builds, and finding a version near this: https://hub.docker.com/r/travisci/ci-sardonyx/tags)
4) docker run --name $BUILDID -dit $INSTANCE /sbin/init
5) docker exec -it $BUILDID bash -l

**Comment by dawnmist** [comment]
Thank you - I'll definitely have a go at that.

Looks interesting - running the tests via react-scripts "just works", but running them through react-app-rewired is definitely hanging. The part you commented out in react-app-rewired is actually the bit where it invokes the react-scripts test script (so in effect commenting it out had simply disabled the tests), but I'd definitely like to find out why it runs via react-scripts but not via react-app-rewired.

**Comment by NoPhaseNoKill** [comment]
That's what was peculiar to me. After checking all of the config etc, it seems to be running fine.

What I just found out, is that it's even getting to the stage where it hits jest.run(argv) inside of the react-scripts/scripts/test.js

Output is as follows:
```
jest.run [Function: run]
argv [
  '--config',
  '{"roots":["<rootDir>/src"],"collectCoverageFrom":["src/**/*.{js,jsx,ts,tsx}","!src/**/*.d.ts"],"setupFiles":["/home/travis/NoPhaseNoKill/dota-stats-ui/node_modules/react-app-polyfill/jsdom.js"],"setupFilesAfterEnv":["<rootDir>/src/setupTests.ts"],"testMatch":["<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}","<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"],"testEnvironment":"jest-environment-jsdom-fourteen","transform":{"^.+\\\\.(js|jsx|ts|tsx)$":"/home/travis/NoPhaseNoKill/dota-stats-ui/node_modules/react-app-rewired/scripts/utils/babelTransform.js","^.+\\\\.css$":"/home/travis/NoPhaseNoKill/dota-stats-ui/node_modules/react-scripts/config/jest/cssTransform.js","^(?!.*\\\\.(js|jsx|ts|tsx|css|json)$)":"/home/travis/NoPhaseNoKill/dota-stats-ui/node_modules/react-scripts/config/jest/fileTransform.js"},"transformIgnorePatterns":["[/\\\\\\\\]node_modules[/\\\\\\\\].+\\\\.(js|jsx|ts|tsx)$","^.+\\\\.module\\\\.(css|sass|scss)$"],"modulePaths":["/home/travis/NoPhaseNoKill/dota-stats-ui/src"],"moduleNameMapper":{"^react-native$":"react-native-web","^.+\\\\.module\\\\.(css|sass|scss)$":"identity-obj-proxy"},"moduleFileExtensions":["web.js","js","web.ts","ts","web.tsx","tsx","json","web.jsx","jsx","node"],"watchPlugins":["jest-watch-typeahead/filename","jest-watch-typeahead/testname"],"rootDir":"/home/travis/NoPhaseNoKill/dota-stats-ui"}',
  '--env',
  '/home/travis/NoPhaseNoKill/dota-stats-ui/node_modules/jest-environment-jsdom/build/index.js'
]
```

**Comment by dawnmist** [comment]
I don't think the tests themselves are actually being run. Jest isn't reporting the individual test names/etc even when the options are provided to report each test individually, which it ought to be at least displaying the first test name as tried even if it got stuck waiting for the test to complete.

**Comment by NoPhaseNoKill** [comment]
The only notable difference I can see between the two are the are the following:

```
"transform": [
                [
                    "^.+\\.(js|jsx|ts|tsx)$",
                    "/home/travis/build/NoPhaseNoKill/dota-stats-ui/node_modules/react-scripts/config/jest/babelTransform.js"
```

and 

```
"transform": [
                [
                    "^.+\\.(js|jsx|ts|tsx)$",
                    "/home/travis/build/NoPhaseNoKill/dota-stats-ui/node_modules/react-app-rewired/scripts/utils/babelTransform.js"
```

**Comment by dawnmist** [comment]
Ok, good catch - I missed the different text on those two lines.

React-scripts version:
```js
'use strict';

const babelJest = require('babel-jest');

module.exports = babelJest.createTransformer({
  presets: [require.resolve('babel-preset-react-app')],
  babelrc: false,
  configFile: false,
});
```
React-app-rewired:
```js
const babelJest = require('babel-jest');

module.exports = babelJest.createTransformer({
  presets: [require.resolve('babel-preset-react-app')],
  plugins: [],
  babelrc: true
});
```

I'll do a quick check on babel-jest to verify that the plugins option still exists - something preventing compilation of the test files themselves could cause the tests to be unable to be run.

**Comment by NoPhaseNoKill** [comment]
Yep was just about to say the same thing. The other alternative is that you need to explicitly define whether the configFile exists (ie is true) in this case

**Comment by NoPhaseNoKill** [comment]
I just checked the exact babel-jest versions being used, and these are both in sync. So we can rule out version disparity. Both are on "24.9.0"

**Comment by NoPhaseNoKill** [comment]
From the typescript types:

plugins (which would indicate you can remove this field):
```
/**
     * List of plugins to load and use
     *
     * Default: `[]`
     */
    plugins?: PluginItem[] | null;
```
config file (which would indicate the dispartiy - your library is setting it to undefined, there's is setting it to false): 
```
/**
     * The config file to load Babel's config from. Defaults to searching for "babel.config.js" inside the "root" folder. `false` will disable searching for config files.
     *
     * Default: `undefined`
     */
    configFile?: string | false | null;
```

**Comment by NoPhaseNoKill** [comment]
I believe the fix will be setting the configFile to false :)

**Comment by NoPhaseNoKill** [comment]
Actually I have a feeling we need to somehow specify where the babelrc gets loaded. This might be causing the issue too. I assume if you have to do something that picks it up.

types below:
```
babelrc?: boolean | null;

    /**
     * Specify which packages should be search for .babelrc files when they are being compiled. `true` to always search, or a path string or an array of paths to packages to search
     * inside of. Defaults to only searching the "root" package.
     *
     * Default: `(root)`
     */
    babelrcRoots?: true | string | string[] | null;
```

**Comment by dawnmist** [comment]
Both undefined and null are treated as "falsey" values, so they would be treated the same as "false" unless babel explicitly tested for exactly false with `if (configFile === false)`.

I've applied a patch using patch-package to the react-app-rewired babelTransform.js file to add configFile=false, but that doesn't seem to have helped.

One thing I did notice however was this line in the install log:
```
ts-jest@25.2.1" has unmet peer dependency "jest@>=25 <26"
```
If jest and babel-jest are at 24.x, shouldn't ts-jest also be a 24.x version?

The other possibility that occurs to me is that the specific version of node.js being used may affect things. I'm currently running with node.js 10, the CI is on 13. What version are you running locally?

**Comment by NoPhaseNoKill** [comment]
Wouldn't have have surprised me if they were explicitly testing for that case in legacy code somewhere. That debunks it though haha.

I'm running version 12 locally. I tried the other day going back to 8, with no success. 

The confusing thing for me is that runs locally fine, which would mean we'd be seeing the same issue locally if it were a dependency issue. There has to be something about the environment

**Comment by dawnmist** [comment]
It doesn't look like ts-jest is actually used at present, so that shouldn't be affecting the tests either.

If I really had to guess, I'd say it almost looks like its doing something like showing the interactive screen for choosing which tests to run instead of doing the CI build version of tests, i.e.:
```
No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.
```
instead of:
```
yarn run v1.22.0
$ CI=true react-app-rewired test
PASS src/tests/App/components/Navigation/Navigation.test.tsx
PASS src/tests/App/App.test.tsx

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.543s, estimated 2s
Ran all test suites.
Done in 2.19s.
```
Node 8 will have its own problems - there's part of the build that was complaining in the docker image that it needed a min version of node 10. I'll give 12 a try as a comparison data point.

**Comment by NoPhaseNoKill** [comment]
The 'CI=true' flag removes the interactive screen, and defaults to running the tests. So it's not that either :(

**Comment by NoPhaseNoKill** [comment]
Also you need to change the below. The --ci flag is deprecated
```
react-app-rewired test --ci --verbose --runInBand --detectOpenHandles
```

to this
```
CI=true react-app-rewired test --verbose --runInBand --detectOpenHandles
```

**Comment by dawnmist** [comment]
_nods on -ci flag_ - I had been trying to test alternative implementations to verify that it really was doing a CI build properly, and --ci was still listed in the jest config docs so I thought it worth at least checking (though it doesn't seem to be helping). I'll pull it back out again.

Ok, the CI flag is definitely being passed through and isn't making any difference. I agree it's got to be something to do with the environment, but I don't know what. I'll keep thinking about it over the next few days, and see what I can turn up.

**Comment by NoPhaseNoKill** [comment]
Roger that. Super peculiar issue. Legit cannot think of what is causing it. Thanks for your help. I'll post a link from here to the original bug lodgement

**Comment by NoPhaseNoKill** [comment]
Have just dockered into said container, and changed the below:
```
const babelJest = require('babel-jest');

module.exports = babelJest.createTransformer({
  presets: [require.resolve('babel-preset-react-app')],
  plugins: [],
  babelrc: false
});
```
Setting babelrc to false, means tests run. So it looks like it's something that happens when this flag is explicitly set to true

**Comment by NoPhaseNoKill** [comment]
From babel's docs:
This may mean we need to add a filename/babelRcRoots
```
babelrc
Type: boolean
Default: true as long as the filename option has been specified
Placement: Allowed in Babel's programmatic options, or inside of the loaded "configFile". A programmatic option will override a config file one.

true will enable searching for configuration files relative to the "filename" provided to Babel.

A babelrc value passed in the programmatic options will override one set within a configuration file.

Note: .babelrc.json files are only loaded if the current "filename" is inside of a package that matches one of the "babelrcRoots" packages.
```

**Comment by dawnmist** [comment]
That last test also turned up some very useful information.

What is supposed to be happening is the setupTests.ts file runs, then the Navigation tests, then setupTests.ts, then the App test. I added a "starting" and a "completed" console message to each of those 3 files in order to track where exactly the hang is occurring.

Inside Travis, the setupTests.ts file _does_ run and complete, but the navigation test never starts. See build: https://travis-ci.com/NoPhaseNoKill/dota-stats-ui/builds/152453891

Babelrc to false means that you're running with the exact same options as you use with react-scripts, so it narrows down the issue to likely being the plugin that you're using in your .babelrc file. Babel _used_ to check for certain specific filenames by default relative to your root directory, so I'd be a little surprised if the issue was that it couldn't find the standard filename in the standard location. I do however remember people having had issues with styled-components & configuration for them in the past, so that may be worth investigating further.

**Comment by NoPhaseNoKill** [comment]
@dawnmist I have found the issue. From reading the docs, you need to add the following to your babelTransform.js

```
const babelJest = require('babel-jest');

module.exports = babelJest.createTransformer({
  presets: [require.resolve('babel-preset-react-app')],
  plugins: [],
  babelrc: true
  rootMode: 'root'
});
```

**Comment by NoPhaseNoKill** [comment]
Please see references types below for more information.
```
/**
     * Specify the "root" folder that defines the location to search for "babel.config.js", and the default folder to allow `.babelrc` files inside of.
     *
     * Default: `"."`
     */
    root?: string | null;

    /**
     * This option, combined with the "root" value, defines how Babel chooses its project root.
     * The different modes define different ways that Babel can process the "root" value to get
     * the final project root.
     *
     * @see https://babeljs.io/docs/en/next/options#rootmode
     */
    rootMode?: 'root' | 'upward' | 'upward-optional';
```

**Comment by NoPhaseNoKill** [comment]
So I think what was happening in my case (and this is just an assumption - I tested and it works) - is that because my file was called .babelrc, and there was no rootMode/root selected - it was only looking for files that had name: "babel.config.js". This theory can be tested, but hooray for finding the issue!

edit: Pretty sure the above is flat out wrong haha. I think it's actually just that we needed to define where to look for any babel config files. Not enough sleep :D

**Comment by NoPhaseNoKill** [comment]
Test output is success. Hooray! Remove the console logs and we should be all good to go :)

The command "CI=true yarn test --listTests" exited with 0.
$ CI=true yarn test --verbose --runInBand
yarn run v1.15.2
$ react-app-rewired test --verbose --runInBand
console.log src/setupTests.ts:5
    setupTests.ts starting
console.log src/setupTests.ts:13
    setupTests.ts completed

**Comment by dawnmist** [comment]
Just tested that - doesn't make a difference. The setupTests.ts script still runs, but none of the tests do. I added console logs to all 3 files, and only the setupTests.ts file's logs are output. It's not a success.

I think it was already finding your .babelrc file - but there's something missing in the setup for the styled components plugin that is causing it to choke when it goes to run tests on components that use it.

However, if styled-components is the reason you're using react-app-rewired, there is an alternative way that you can use it with the newer versions of create-react-app, by using the babel macro form for importing them: https://styled-components.com/docs/tooling#babel-macro

**Comment by NoPhaseNoKill** [comment]
I'm getting the below when running it inside of the docker container:

```
travis@aa7a3deb384c:~/NoPhaseNoKill/dota-stats-ui$ yarn test
yarn run v1.15.2
$ CI=true react-app-rewired test
 PASS  src/tests/App/App.test.tsx
 PASS  src/tests/App/components/Navigation/Navigation.test.tsx

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        3.565s
Ran all test suites.
```

**Comment by dawnmist** [comment]
Note - A success case in travis for this pull should be showing:
```
yarn run v1.22.0                                                                                                                                                                                                                             
$ react-app-rewired test --verbose --runInBand                                                                                                                                                                                               
PASS src/tests/App/components/Navigation/Navigation.test.tsx
  ✓ renders navigation buttons when app starts (62ms)

  console.log src/setupTests.ts:5
    setupTests.ts starting

  console.log src/setupTests.ts:13
    setupTests.ts completed

  console.log src/tests/App/components/Navigation/Navigation.test.tsx:7
    Navigation test starting

  console.log src/tests/App/components/Navigation/Navigation.test.tsx:13
    Navigation test completed

  console.log src/setupTests.ts:5
    setupTests.ts starting

  console.log src/setupTests.ts:13
    setupTests.ts completed

  console.log src/tests/App/App.test.tsx:6
    App.test.tsx starting

  console.log src/tests/App/App.test.tsx:10
    App.test.tsx completed

PASS src/tests/App/App.test.tsx
  ✓ renders without crashing (17ms)

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.699s, estimated 3s
Ran all test suites.
Done in 3.38s.     
```

I didn't manage to work out how to get travis itself running in the container.

**Comment by dawnmist** [comment]
Have a look at this issue: https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/issues/54

**Comment by NoPhaseNoKill** [comment]
I had it working in the container. And now for some reason it wont :(

**Comment by dawnmist** [comment]
I'd tried testing the change to the babelTransform you gave here, but it still wasn't working in Travis.

There is mention that babel-plugin-styled-components-css-namespace may not be compatible with versions of node > 12.10. I've tried setting off a test with node version of 10, but Travis hasn't triggered for that commit yet. (And I see that the styled-components-css-namespace hasn't got the babel-macro functionality yet, so that isn't an alternative option for you.)

**Comment by NoPhaseNoKill** [comment]
I feel like I'm going crazy haha. I literally just had it working in the container and now I can't reproduce. Ughhhh

**Comment by dawnmist** [comment]
Do I need to rebase on master to get Travis builds going again?

**Comment by dawnmist** [comment]
BINGO!

Set your node version to 10 in master without any other changes, and retest master.

If that works there, the cause of the issue is that styled-components-css-namespace isn't compatible with versions of node.js after 12.10 as documented in [issue 54](https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/issues/54) in their github repo.

**Comment by NoPhaseNoKill** [comment]
You're basically my hero and I am forever in debt :)

**Comment by NoPhaseNoKill** [comment]
So must have been the combination of the rootMode + version 10?

**Comment by NoPhaseNoKill** [comment]
Nope just confirmed it was literally to do with node version. Thank you so much for your help :)

**Comment by dawnmist** [comment]
I don't think even the rootMode was needed - just the version of node.js, particularly as you didn't apply the patch for adding rootMode to the babelTransform.js file to master. ;)

**Comment by dawnmist** [comment]
You're welcome for the help - was a tricky issue to track. In the end it was seeing that the setupTests.ts file _was_ actually being run that made me start looking at the issue lists for the plugins you were using, and from there stumbled on the issue that said that it was incompatible with more recent versions of node.js.

**Comment by NoPhaseNoKill** [comment]
Ah ha. Well there you go. I figured I could ultimately move to the macros as suggested, but once a dev gets in their mind that a problem needs to be solved - well you know how that ends haha.

**Pull request closed without merging**
